### ISSUE TITLE
Model Accessors/Properties

### ISSUE THREAD

**Issue by dixonwhitmire** [LinuxForHealth/x12#27]
X12 transaction models can be cumbersome to navigate due to the nested and hierarchical nature of some of the transaction sets such as eligibility and claim status. Let's make things a bit easier by adding "accessor" methods for the entities in the transaction set. An entity is a record which is comprised of one or more loops.

For example in the Eligibility Inquiry model (270) we could add a subscriber property:

```python
@property
def subscriber(self, return_first=True) -> Union[Dict,List]:
   """
    Returns all segments related to a subscriber record across all subscriber loops.
    The return_first parameter is used to indicate if the records for a single subscriber
     are returned or if all subscriber records are returned.
    """
    pass
```

The `return_first` parameter will default to True for each implementation. The majority of x12 transactions convey data for a single member rather than batch. The one notable exception is the 834 (Benefit Enrollment) format.

Finally, adding properties to the transaction set models provides a greater and simpler DX experience.

**Comment by ccorley** [comment]
I wonder if we don't need a lower-level accessor, like:

@property
def subModel(self, segment_name: string, identifier: string) -> Dict:
     """
     Returns the dict for a specific segment.
     """
     
 We could use this to ask for, for example, the "NM1" "IL" segment dict and easily access the values we need.

**Comment by dixonwhitmire** [comment]
> I wonder if we don't need a lower-level accessor, like:
> 
> ```
> @property
> def subModel(self, segment_name: string, identifier: string) -> Dict:
>      """
>      Returns the dict for a specific segment.
>      """
> ```
> 
> We could use this to ask for, for example, the "NM1" "IL" segment dict and easily access the values we need.

That's a great point @ccorley we may need to add the "loop_name" to the signature (we have enumerations for these) as there could be multiple segments of the same name in the transaction set. We may still need to support a return type of `List[Dict]` due to the "reuse".

**Comment by dixonwhitmire** [comment]
Met with @ccorley to discuss the initial implementation. We will provide accessors for each high level loop with an additional parameter to indicate if we want the first result. This will default to "true" (in 7 years at PokitDok I never saw a multiple record eligibility transaction).
